# Generated by Django 4.2.4 on 2023-10-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='end_time',
            field=models.TimeField(verbose_name='Hodimning ish vaqtining tugashi :'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_time',
            field=models.TimeField(verbose_name='Hodimning ish boshlash vaqti :'),
        ),
    ]
