# Generated by Django 4.2.4 on 2023-10-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_employee_end_time_alter_employee_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='specialty',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Hodimning mutaxassisligi'),
        ),
    ]
