# Generated by Django 4.2.4 on 2023-10-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_patient_doctor_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='private_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.private_room', verbose_name='Hodimning honasi :'),
        ),
    ]
