# Generated by Django 4.2.4 on 2023-10-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_employee_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='day',
            field=models.IntegerField(verbose_name='Bemorning honadagi kuni :'),
        ),
    ]
