# Generated by Django 4.2.4 on 2023-10-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_employee_private_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='time',
            field=models.IntegerField(default=1, verbose_name='Hodimning jami ishlash vaqti :'),
            preserve_default=False,
        ),
    ]
