# Generated by Django 4.2.4 on 2023-10-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_patient_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(verbose_name='Bemor honasining yaratilgan vaqti :'),
        ),
    ]
