# Generated by Django 4.2.4 on 2023-10-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_employee_section_alter_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status_gender',
            field=models.IntegerField(choices=[(1, 'Famele'), (2, 'Male')], default=1, verbose_name='Hona moslashishi (Masalan: Ayol) :'),
            preserve_default=False,
        ),
    ]
